import time;

sleep_time = .2 

print("Helloooooo!")
time.sleep(sleep_time)
print("Welcome to Python, land of lists, dictionaries, and tuples")
time.sleep(sleep_time)
print("You'll find no braces or semicolons here")
time.sleep(sleep_time)
print("")
print("This tutorial contains partially working code to help you learn Python.")
time.sleep(sleep_time)
print("You have been chosen to fix it! The fate of Spamalot rests in your hands!")
time.sleep(sleep_time)

print("")
print("Your first challenge is to import the code for a fibonacci function")
time.sleep(sleep_time)
print("Warning: this may be a little trickier than it seems.")
time.sleep(sleep_time)
print("Read error messages carefully, and look online for help if you need it. Good luck!")
time.sleep(sleep_time)
print("Attempting to call fib(4)...")
time.sleep(sleep_time)
print(fib(4))

print("Huzzah! Great job!")
time.sleep(sleep_time)
print("You are worthy of the title Pythonic " + u'\u3082' + u'\u3084' + u'\u3057')
time.sleep(sleep_time)
print("The knights of Spamalot have been challenged by the Shadow Lord Tim to calculate fib(100)!!!")
time.sleep(sleep_time)
print("It's either that or chopping down the thickest herring in the forest...")
time.sleep(sleep_time)
print("What are you waiting for?? Go fix the fib() code so it doesn't take 10 years! Use the mighty lists of Python!")
time.sleep(sleep_time)
print("Calling fib(100)...")
time.sleep(5)
print("Gonna be here a while...")
ans = fib(100)
print(ans)
if(ans == 354224848179261915075):
    print("AMAZING!")
